spring.application.name=SummarySphere-Backend
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=${OPENROUTER_BASE_URL}
spring.ai.openai.chat.options.model=${OPENROUTER_CHAT_MODEL}
spring.ai.model.chat=openai
spring.ai.model.embedding.text=google-genai

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.enabled=false
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance

spring.jpa.hibernate.ddl-auto=update
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

spring.autoconfigure.exclude=org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_EMAIL}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
resend.api.key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME}
